### ISSUE TITLE
還需要 調整/新增 語意化洨安的顏色

### ISSUE THREAD

**Issue by gnehs** [gnehs/Tocas-UI-Xiaoan#13]
把你的配種數據交上來吧 😀

**Comment by gnehs** [comment]
@gnehs 貓貓

**Comment by lekoOwO** [comment]
exceedingly light blue xiaoan
`filter: invert(0.9) contrast(65%) sepia(100%) hue-rotate(129.5deg) grayscale(0%) blur(0px) brightness(100%) saturate(100%);`

gloomy xiaoan
`filter: invert(1) contrast(25%) sepia(53%) hue-rotate(165.5deg) grayscale(0%) blur(0px) brightness(80%) saturate(100%);`

NTR xiaoan
`filter: invert(0.87) contrast(32%) sepia(100%) hue-rotate(75.5deg) grayscale(0%) blur(1.1px) brightness(87%) saturate(100%);`

love xiaoan
`filter: invert(0.95) contrast(32%) sepia(100%) hue-rotate(266.5deg) grayscale(0%) blur(0px) brightness(100%) saturate(100%);`

early spring xiaoan
`filter: invert(1) contrast(200%) sepia(0%) hue-rotate(0deg) grayscale(0%) blur(0px) brightness(100%) saturate(0%);`


其實我覺得
`filter: invert(0.95) contrast(32%) sepia(100%) hue-rotate(0deg) grayscale(0%) blur(0px) brightness(100%) saturate(100%);`下，hue-rotate不管怎麼調都很好看XDD

隨便拉的，品質不保證(X

**Comment by gnehs** [comment]
@rexx0520 好的，感謝提供
