### ISSUE TITLE
新的品種：愛心洨安

### ISSUE THREAD

**Issue by gnehs** [gnehs/Tocas-UI-Xiaoan#15]
有正身跟反色

**Comment by gnehs** [comment]
測試

**Comment by gnehs** [comment]
@gnehs 完成！

**Comment by lekoOwO** [comment]
@gnehs test

**Comment by gnehs** [comment]
![heart instead](https://user-images.githubusercontent.com/16719720/27620269-0b80d554-5bfb-11e7-9897-700ea7ce21a4.png)
![heart](https://user-images.githubusercontent.com/16719720/27620270-0ba954b6-5bfb-11e7-984a-799f8b3c2daf.png)
好了
